[package]
name = "scalerpc"
version = "0.1.0"
edition = "2021"

[dependencies]
mlx5 = { version = "0.1.0", path = "../mlx5" }
libc = "0.2"
minstant = "0.1"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "pingpong"
harness = false

[lints.clippy]
type_complexity = "allow"
