name: Build LaTeX

on:
  push:
    paths:
      - "papers/ipsj-hpc203/**"
  pull_request:
    paths:
      - "papers/ipsj-hpc203/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: papers/ipsj-hpc203
          tags: ipsj-latex:latest
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build PDF
        run: docker run --rm -v ${{ github.workspace }}/papers/ipsj-hpc203:/workdir ipsj-latex latexmk hpc203.tex

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: ipsj-hpc203
          path: papers/ipsj-hpc203/hpc203.pdf
